# Site settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Junteng Liu"
title_separator          : "-"
name                     : "Junteng Liu"
description              : "First-year PhD candidate at HKUST NLP Group"
url                      : "https://toolathlonmsft.github.io"
baseurl                  : "/LJT-Homepage"
repository               : "toolathlonmsft/LJT-Homepage"

# Site author
author:
  avatar           :
  name             : "Junteng Liu"
  pronouns         :
  bio              : "First-year PhD candidate at HKUST NLP Group"
  location         :
  employer         :
  uri              :
  email            : "jliugi@connect.ust.hk"

  # Academic profiles
  academia         :
  arxiv            :
  googlescholar    : "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"
  inspire-hep      :
  impactstory      :
  orcid            :
  semantic         :
  ssrn             :
  pubmed           :
  researchgate     :
  scopus           :
  zotero           :

  # Repositories and software development
  bitbucket        :
  codepen          :
  dribbble         :
  github           : "Vicent0205"
  kaggle           :
  stackoverflow    :

  # Social media
  artstation       :
  bluesky          :
  facebook         :
  flickr           :
  foursquare       :
  goodreads        :
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         :
  mastodon         :
  medium           :
  pinterest        :
  soundcloud       :
  steam            :
  telegram         :
  tumblr           :
  twitter          : "junteng88716710"
  vine             :
  weibo            :
  wikipedia        :
  xing             :
  youtube          :
  zhihu            :

# Site behavior
teaser                   :
breadcrumbs              : false
words_per_minute         : 160
future                   : false
read_more                : "disabled"
talkmap_link             : false
comments:
  provider               : false
atom_feed:
  hide                   : true
  path                   :

# SEO
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :
twitter:
  username               : "junteng88716710"
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :
og_description           :
social:
  type                   : Person
  name                   : "Junteng Liu"
  links:
    - "https://github.com/Vicent0205"
    - "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"

# Analytics
analytics:
  provider               : false

# Reading files
include:
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .devcontainer
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - _drafts
  - _portfolio
  - _posts
  - _publications
  - _talks
  - _teaching
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README.md
  - config
  - docker-compose.yaml
  - files
  - images
  - local
  - log
  - markdown_generator
  - node_modules
  - package.json*
  - Rakefile
  - scripts
  - talkmap
  - talkmap.ipynb
  - talkmap.py
  - talkmap_out.ipynb
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Page defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Output
permalink: /:categories/:title/
timezone: Etc/UTC

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML compression
compress_html:
  clippings: all
  ignore:
    envs: development
